log:
  # 日志文件路径
  path: logs.log
  # 日志模式 console file
  run_type: console
  # 日志级别 debug  info  error
  level: debug
  # 每个日志文件保存大小 20M
  max_size: 20
  # 保留 N 个备份
  max_backups: 20
  # 保留 N 天
  max_age: 7

gorm:
  # 驱动名称 mysql postgresql sqlite
  driver: mysql
  # 连接地址
  dsn: root:123456@tcp(127.0.0.1:3306)/webapi?charset=utf8mb4&parseTime=True&loc=Local
  # 模式(postgresql专用)
  schema: public
  # 设置空闲连接池中连接的最大数量
  max_idle_count: 10
  # 设置打开数据库连接的最大数量
  max_open_count: 100
  # 设置了连接可复用的最大时间(要比数据库设置连接超时时间少)(单位秒)
  max_life_time: 300

mongodb:
  uri: mongodb://127.0.0.1:27017
  database: "test"
  max_pool_size: 100
  min_pool_size: 5
  max_conn_idle_time: 300

redis:
  # 多个地址是以 , 分割
  addr: 127.0.0.1:6379
  # 选择N号数据库
  db_num: 0
  # 密码
  password:
  # 最大链接数
  pool_size: 100
  # 空闲链接数
  min_idle_conn: 5

jwt:
  # 加密密钥
  secret_key: b9f07bfd4eaf7b8a63d9
  # 过期时长(单位秒)
  expire_time: 604800
