package header

// Common MIME types
const (
	TextHTML               = "text/html"
	TextPlain              = "text/plain"
	TextXML                = "text/xml"
	TextCSS                = "text/css"
	TextJavaScript         = "text/javascript"
	MultipartForm          = "multipart/form-data"
	ApplicationForm        = "application/x-www-form-urlencoded"
	ApplicationOctetStream = "application/octet-stream"
	ApplicationJSON        = "application/json"
	ApplicationJavaScript  = "application/javascript"
	ApplicationXML         = "application/xml"
	ApplicationCBOR        = "application/cbor"
	ApplicationMsgPack     = "application/vnd.msgpack"

	TextHTMLCharsetUTF8        = "text/html; charset=utf-8"
	TextPlainCharsetUTF8       = "text/plain; charset=utf-8"
	TextXMLCharsetUTF8         = "text/xml; charset=utf-8"
	TextCSSCharsetUTF8         = "text/css; charset=utf-8"
	TextJavaScriptCharsetUTF8  = "text/javascript; charset=utf-8"
	ApplicationXMLCharsetUTF8  = "application/xml; charset=utf-8"
	ApplicationJSONCharsetUTF8 = "application/json; charset=utf-8"
)

// Common HTTP Headers
const (
	Authorization                      = "Authorization"
	ProxyAuthenticate                  = "Proxy-Authenticate"
	ProxyAuthorization                 = "Proxy-Authorization"
	WWWAuthenticate                    = "WWW-Authenticate"
	Age                                = "Age"
	CacheControl                       = "Cache-Control"
	ClearSiteData                      = "Clear-Site-Data"
	Expires                            = "Expires"
	Pragma                             = "Pragma"
	Warning                            = "Warning"
	AcceptCH                           = "Accept-CH"
	AcceptCHLifetime                   = "Accept-CH-Lifetime"
	ContentDPR                         = "Content-DPR"
	DPR                                = "DPR"
	EarlyData                          = "Early-Data"
	SaveData                           = "Save-Data"
	ViewportWidth                      = "Viewport-Width"
	Width                              = "Width"
	ETag                               = "ETag"
	IfMatch                            = "If-Match"
	IfModifiedSince                    = "If-Modified-Since"
	IfNoneMatch                        = "If-None-Match"
	IfUnmodifiedSince                  = "If-Unmodified-Since"
	LastModified                       = "Last-Modified"
	Vary                               = "Vary"
	Connection                         = "Connection"
	KeepAlive                          = "Keep-Alive"
	Accept                             = "Accept"
	AcceptCharset                      = "Accept-Charset"
	AcceptEncoding                     = "Accept-Encoding"
	AcceptLanguage                     = "Accept-Language"
	Cookie                             = "Cookie"
	Expect                             = "Expect"
	MaxForwards                        = "Max-Forwards"
	SetCookie                          = "Set-Cookie"
	AccessControlAllowCredentials      = "Access-Control-Allow-Credentials"
	AccessControlAllowHeaders          = "Access-Control-Allow-Headers"
	AccessControlAllowMethods          = "Access-Control-Allow-Methods"
	AccessControlAllowOrigin           = "Access-Control-Allow-Origin"
	AccessControlExposeHeaders         = "Access-Control-Expose-Headers"
	AccessControlMaxAge                = "Access-Control-Max-Age"
	AccessControlRequestHeaders        = "Access-Control-Request-Headers"
	AccessControlRequestMethod         = "Access-Control-Request-Method"
	Origin                             = "Origin"
	TimingAllowOrigin                  = "Timing-Allow-Origin"
	XPermittedCrossDomainPolicies      = "X-Permitted-Cross-Domain-Policies"
	DNT                                = "DNT"
	Tk                                 = "Tk"
	ContentDisposition                 = "Content-Disposition"
	ContentEncoding                    = "Content-Encoding"
	ContentLanguage                    = "Content-Language"
	ContentLength                      = "Content-Length"
	ContentLocation                    = "Content-Location"
	ContentType                        = "Content-Type"
	Forwarded                          = "Forwarded"
	Via                                = "Via"
	XForwardedFor                      = "X-Forwarded-For"
	XForwardedHost                     = "X-Forwarded-Host"
	XForwardedProto                    = "X-Forwarded-Proto"
	XForwardedProtocol                 = "X-Forwarded-Protocol"
	XForwardedSsl                      = "X-Forwarded-Ssl"
	XUrlScheme                         = "X-Url-Scheme"
	Location                           = "Location"
	From                               = "From"
	Host                               = "Host"
	Referer                            = "Referer"
	ReferrerPolicy                     = "Referrer-Policy"
	UserAgent                          = "User-Agent"
	Allow                              = "Allow"
	Server                             = "Server"
	AcceptRanges                       = "Accept-Ranges"
	ContentRange                       = "Content-Range"
	IfRange                            = "If-Range"
	Range                              = "Range"
	ContentSecurityPolicy              = "Content-Security-Policy"
	ContentSecurityPolicyReportOnly    = "Content-Security-Policy-Report-Only"
	CrossOriginResourcePolicy          = "Cross-Origin-Resource-Policy"
	ExpectCT                           = "Expect-CT"
	PermissionsPolicy                  = "Permissions-Policy"
	PublicKeyPins                      = "Public-Key-Pins"
	PublicKeyPinsReportOnly            = "Public-Key-Pins-Report-Only"
	StrictTransportSecurity            = "Strict-Transport-Security"
	UpgradeInsecureRequests            = "Upgrade-Insecure-Requests"
	XContentTypeOptions                = "X-Content-Type-Options"
	XDownloadOptions                   = "X-Download-Options"
	XFrameOptions                      = "X-Frame-Options"
	XPoweredBy                         = "X-Powered-By"
	XXSSProtection                     = "X-XSS-Protection"
	LastEventID                        = "Last-Event-ID"
	NEL                                = "NEL"
	PingFrom                           = "Ping-From"
	PingTo                             = "Ping-To"
	ReportTo                           = "Report-To"
	TE                                 = "TE"
	Trailer                            = "Trailer"
	TransferEncoding                   = "Transfer-Encoding"
	SecFetchSite                       = "Sec-Fetch-Site"
	SecWebSocketAccept                 = "Sec-WebSocket-Accept"
	SecWebSocketExtensions             = "Sec-WebSocket-Extensions"
	SecWebSocketKey                    = "Sec-WebSocket-Key"
	SecWebSocketProtocol               = "Sec-WebSocket-Protocol"
	SecWebSocketVersion                = "Sec-WebSocket-Version"
	AcceptPatch                        = "Accept-Patch"
	AcceptPushPolicy                   = "Accept-Push-Policy"
	AcceptSignature                    = "Accept-Signature"
	AltSvc                             = "Alt-Svc"
	Date                               = "Date"
	Index                              = "Index"
	LargeAllocation                    = "Large-Allocation"
	Link                               = "Link"
	PushPolicy                         = "Push-Policy"
	RetryAfter                         = "Retry-After"
	ServerTiming                       = "Server-Timing"
	Signature                          = "Signature"
	SignedHeaders                      = "Signed-Headers"
	SourceMap                          = "SourceMap"
	Upgrade                            = "Upgrade"
	XDNSPrefetchControl                = "X-DNS-Prefetch-Control"
	XPingback                          = "X-Pingback"
	XRequestID                         = "X-Request-ID"
	XRequestedWith                     = "X-Requested-With"
	XResponseTime                      = "X-Response-Time"
	XRobotsTag                         = "X-Robots-Tag"
	XUACompatible                      = "X-UA-Compatible"
	AccessControlAllowPrivateNetwork   = "Access-Control-Allow-Private-Network"
	AccessControlRequestPrivateNetwork = "Access-Control-Request-Private-Network"
)
